### PR TITLE
Create modifiedQuestDescriptions.sql

### PR DESCRIPTION
**Pull request by JeFawk**
Fix for issue #6 Quest descriptions and punctuation marks. 

Created a program that parses the description and objectives and fixes all the punctuation marks and spaces.

Before:
before

After:
after

Applying the fix via Execute SQL file:
execute sql statement

### CODE REVIEW

**Comment by Vallaquenta** [comment]
The file is obsolete now right? So I think we can get rid of the /world folder? Just to tidy things up ^_^

**Comment by JeFawk** [comment]
The changes seem to have moved in the development folder which apparently contains my modifications.

**Comment by Vallaquenta** [comment]
Yep I know, that's why the folder now seems obsolete right?

**Comment by JeFawk** [comment]
Yeah

**Comment by MaxHayman** [comment]
So the changes are already in the new database?

**Comment by JeFawk** [comment]
The quests.sql from https://github.com/WarEmu/WarDB/tree/master/development/war_world seems to be the one I pushed with my app, you know that was fixing the punctuation. 

I can verify this when I get home.

**Comment by Vallaquenta** [comment]
I've had a look at it today. Seems like it is the right version, not entirely sure though.

**Comment by JeFawk** [comment]
The issue is still present; the fix was not applied.

**Pull request merged**
