### PR TITLE
Create ability_effects

### PR DESCRIPTION
**Pull request by bozzax**
Break down of abilities into sub effects

### CODE REVIEW

**Comment by MaxHayman** [comment]
Did you make these yourself or?

**Comment by privatewar** [comment]
Yes I've done 99% of it myself (except some merged info from the wardb table ability_stats). I'll try join waremu irc if you have questions. Effects are based on warspec3.0.

Noticed file itself was missing first row https://drive.google.com/file/d/0B9HeNwtoZF-SbG5Fc2RxMWlCNDg/edit?usp=sharing

**Comment by privatewar** [comment]
May I politely ask why you don't add this to the open source DB?

**Comment by MaxHayman** [comment]
Sorry, been really busy working on some other things. I was gonna try and wait until this was supported in the emulator.

**Pull request merged**
